In [6]:
import numpy as np
a=np.array([5,4,9,10])
print(a)

[ 5  4  9 10]


In [14]:
import numpy as np
b=np.array([[5,4,9,10],[3,0,2,1]])
print(b)


[[ 5  4  9 10]
 [ 3  0  2  1]]


In [13]:
import numpy as np
c=np.array([[3,0,2,1]])
print(b)


[[3 0 2 1]]


In [15]:
np.add(a,c)

array([[ 8,  4, 11, 11]])

In [16]:
np.sin(c)

array([[0.14112001, 0.        , 0.90929743, 0.84147098]])

[[ 5  4  9 10]
 [ 3  0  2  1]]
