In [5]:
import math

In [6]:
math.log(5)

1.6094379124341003

In [7]:
import random
random.randint(0,10)

3

In [8]:
# method encargado de brindarme ayuda visual sobre el contenido 
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [10]:
import numpy as np

In [12]:
a = np.array([5,4,9,10])
print(a)

[ 5  4  9 10]


In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
a.ndim

1

In [17]:
a.shape

(4,)

In [18]:
a.size

4

In [27]:
b = np.array([[5,4,9,10],[4,5,6,7]])
print(b)

[[ 5  4  9 10]
 [ 4  5  6  7]]


In [21]:
print(type(a))

<class 'numpy.ndarray'>


In [29]:
b.ndim

2

In [32]:
b.shape

(2, 4)

In [33]:
b.size

8