>> Formato: Entregar un archivo con formato .ipynb. Debe tener el nombre “Arrays+Apellido”. 
Sugerencia: Preparar el código y probar los resultados con distintas entradas.
>> Consigna: 
Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.
Recordar los ejercicios con funciones para cálculo de factorial y suma de serie de la Clase 02. Repetir ambos ejercicios, pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.
En este link se provee un archivo con los resultados de la Encuesta de Sueldos de Openqube de Febrero 2020 (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ ), Calcular y comparar media y mediana de los sueldos netos.

>>Aspectos a incluir en el entregable:
El código debe estar hecho en un notebook y debe estar probado.


>> Consigna: 
Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.

In [38]:
# importar la libreria
import numpy as np

In [48]:
Np_random_dimensiones = np.random.randint( 100,size=(4)) #valores aleatorios
Np_random_dimensiones


array([34, 77, 11, 20])

In [49]:
Np_random_dimensiones.mean()

35.5

In [50]:
Np_random_dimensiones

array([34, 77, 11, 20])

In [51]:
np.median(Np_random_dimensiones)

27.0

In [52]:
from statistics import median
median(Np_random_dimensiones)

27.0

>> Consigna: 
Recordar los ejercicios con funciones para cálculo de factorial y suma de serie de la Clase 02. 
Repetir ambos ejercicios, pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.

cálculo de factorial

In [57]:
np.math.factorial(0)

1

In [58]:
np.math.factorial(5)

120

In [62]:
import numpy as np
from scipy.special import factorial #conda install scipy
myArrayFactorial = np.array([[1,2,3],[4,5,6]]) 

In [66]:
factorial(myArrayFactorial)

array([[  1.,   2.,   6.],
       [ 24., 120., 720.]])

suma de serie 

In [80]:
import numpy as np
myArraySerie = np.arange(1,10).reshape(3,3)
print(myArraySerie)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
np.sum(myArraySerie, axis=0)

array([12, 15, 18])

In [82]:
myArraySerie = np.arange(1,10)
print(myArraySerie)

[1 2 3 4 5 6 7 8 9]


In [83]:
np.sum(myArraySerie, axis=0)

45